version: '3.7'

services:
  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    env_file:
      - src/.env
    ports:
      - '${SERVER_PORT}:3000'
    links:
      - storage

  storage:
    build:
      context: ./
      dockerfile: ./docker/storage/Dockerfile
    env_file:
      - src/.env
    ports:
      - '${STORAGE_PORT}:50051'
