version: '3.7'

services:
  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    environment:
      STORAGE_URL: 'storage:50051'
      PAGE_WAIT_TIME: 5
    ports:
      - '${SERVER_PORT}:3000'
    links:
      - storage

  storage:
    build:
      context: ./
      dockerfile: ./docker/storage/Dockerfile
    ports:
      - '${STORAGE_PORT}:50051'
